/**
 * Financial Escape Room V3 — randomized finance question bank
 * 72 handcrafted questions: 24 per difficulty.
 * Each game samples 4 different questions from the selected level and
 * avoids repeating a category in the same run.
 */

const QUESTION_BANK = {
  easy: [
    {id:'e01',category:'Budgeting',type:'numeric',title:'The Missing Budget Line',story:'A student earns ₹28,000 this month. Rent is ₹10,000, food is ₹5,500 and transport is ₹2,500.',prompt:'How much remains after these three expenses? (₹)',answer:'10000',codeFragment:'4',hint:'Add the three expenses first.',explanation:'₹10,000 + ₹5,500 + ₹2,500 = ₹18,000. ₹28,000 − ₹18,000 = ₹10,000.'},
    {id:'e02',category:'Budgeting',type:'mcq',title:'Need or Want?',story:'You have ₹2,000 left for the week. Your phone bill is due, but you also want a new pair of headphones.',prompt:'Which should normally be prioritised first?',options:[['A','The due essential bill'],['B','The headphones'],['C','Both by using a new loan']],answer:'A',codeFragment:'7',hint:'Think about essential obligations before optional purchases.',explanation:'Essential, due expenses should generally be handled before discretionary purchases.'},
    {id:'e03',category:'Interest',type:'numeric',title:'Simple Interest Check',story:'A deposit of ₹8,000 earns simple interest at 5% per year for 2 years.',prompt:'How much interest is earned? (₹)',answer:'800',codeFragment:'2',hint:'Use P × R × T / 100.',explanation:'₹8,000 × 5 × 2 / 100 = ₹800.'},
    {id:'e04',category:'Interest',type:'mcq',title:'Interest Rate Meaning',story:'A savings account advertises 6% annual interest.',prompt:'What does the 6% rate describe?',options:[['A','The annual rate applied to the relevant balance'],['B','A guaranteed 6% increase every month'],['C','A fee charged every time you withdraw']],answer:'A',codeFragment:'8',hint:'The word annual tells you the time period.',explanation:'A 6% annual rate is a yearly interest rate; the actual credited amount depends on the account terms.'},
    {id:'e05',category:'Inflation',type:'numeric',title:'Inflation in Action',story:'A notebook costs ₹200 today. Its price rises by 10%.',prompt:'What is the new price? (₹)',answer:'220',codeFragment:'5',hint:'Find 10% of ₹200 and add it.',explanation:'10% of ₹200 is ₹20, so the new price is ₹220.'},
    {id:'e06',category:'Inflation',type:'mcq',title:'Purchasing Power',story:'Prices rise while your savings balance stays exactly the same.',prompt:'What generally happens to the purchasing power of that unchanged cash balance?',options:[['A','It increases'],['B','It decreases'],['C','It becomes unlimited']],answer:'B',codeFragment:'1',hint:'If the same money buys fewer goods, purchasing power has changed.',explanation:'Inflation generally reduces the purchasing power of money when its value does not grow at the same pace.'},
    {id:'e07',category:'Banking',type:'mcq',title:'Emergency Fund Location',story:'You are building an emergency fund that may be needed quickly.',prompt:'Which feature is most important for this money?',options:[['A','Easy access and liquidity'],['B','A promise of huge returns'],['C','A lock-in with no withdrawals']],answer:'A',codeFragment:'6',hint:'Emergency money needs to be available when an emergency happens.',explanation:'Liquidity and accessibility are important characteristics of an emergency fund.'},
    {id:'e08',category:'Banking',type:'truefalse',title:'OTP Rule',story:'A caller says they need your one-time password to “reverse” a bank transaction.',prompt:'Should you share the OTP with the caller?',options:[['TRUE','Yes, if they know your name'],['FALSE','No, do not share it']],answer:'FALSE',codeFragment:'3',hint:'An OTP is an authentication credential.',explanation:'You should not disclose an OTP to an unsolicited caller or message.'},
    {id:'e09',category:'Credit',type:'mcq',title:'Credit Limit Is Not Cash',story:'Your card shows a ₹50,000 credit limit, but you have only ₹8,000 in your bank account.',prompt:'What is the ₹50,000 figure?',options:[['A','Money already in your bank account'],['B','The maximum credit available under the card terms'],['C','Your guaranteed monthly income']],answer:'B',codeFragment:'9',hint:'A credit limit is not the same as cash in your account.',explanation:'A credit limit is the maximum amount the issuer allows you to borrow on the card, subject to its terms.'},
    {id:'e10',category:'Credit',type:'numeric',title:'Card Balance',story:'You spend ₹3,200 on a card and later repay ₹2,000.',prompt:'Ignoring interest and fees, how much remains unpaid? (₹)',answer:'1200',codeFragment:'4',hint:'Subtract the repayment from the spending.',explanation:'₹3,200 − ₹2,000 = ₹1,200.'},
    {id:'e11',category:'Insurance',type:'mcq',title:'Why Insurance?',story:'A family wants protection from a large unexpected medical expense.',prompt:'What is the main purpose of insurance?',options:[['A','Transfer certain financial risks to an insurer under a policy'],['B','Guarantee that nothing bad can happen'],['C','Make every investment profitable']],answer:'A',codeFragment:'7',hint:'Insurance manages financial risk; it does not remove the event itself.',explanation:'Insurance can provide financial protection against covered risks in exchange for premiums and subject to policy terms.'},
    {id:'e12',category:'Insurance',type:'truefalse',title:'Policy Terms Matter',story:'A policy document lists exclusions and conditions.',prompt:'Can an insurer always pay every claim regardless of the policy wording?',options:[['TRUE','Yes'],['FALSE','No, coverage depends on the policy terms']],answer:'FALSE',codeFragment:'2',hint:'Coverage is defined by the contract.',explanation:'Claims are assessed according to the policy’s coverage, exclusions, conditions and applicable rules.'},
    {id:'e13',category:'Investing',type:'mcq',title:'Diversification Basics',story:'Investor A puts all savings into one company. Investor B spreads money across several investments.',prompt:'Which approach generally reduces single-company concentration risk?',options:[['A','Investor A'],['B','Investor B'],['C','Neither can reduce concentration risk']],answer:'B',codeFragment:'8',hint:'Concentration means depending heavily on one investment.',explanation:'Spreading investments can reduce the impact of one company performing badly, although diversification does not remove all risk.'},
    {id:'e14',category:'Investing',type:'mcq',title:'Risk and Return',story:'Two investments have different levels of uncertainty.',prompt:'Which statement is generally more accurate?',options:[['A','Higher potential return can come with higher risk'],['B','Higher return is always guaranteed'],['C','Risk and return are completely unrelated']],answer:'A',codeFragment:'5',hint:'Think about the trade-off investors face.',explanation:'Potentially higher returns are often associated with higher uncertainty; there is no guarantee of a higher return.'},
    {id:'e15',category:'Mutual Funds',type:'mcq',title:'What Is Diversified?',story:'A mutual fund pools money from many investors and invests according to its stated strategy.',prompt:'What does “diversified” most directly describe?',options:[['A','Holding exposure to multiple securities or assets'],['B','Guaranteeing no losses'],['C','Keeping all money in one company']],answer:'A',codeFragment:'1',hint:'Diversification is about spreading exposure.',explanation:'A diversified fund can spread exposure across multiple securities or asset classes, depending on its mandate.'},
    {id:'e16',category:'Mutual Funds',type:'mcq',title:'NAV Snapshot',story:'A fund has 1,000 units outstanding and net assets worth ₹50,000.',prompt:'What is the NAV per unit? (₹)',options:[['A','₹5'],['B','₹50'],['C','₹500']],answer:'B',codeFragment:'6',hint:'Divide net assets by units.',explanation:'₹50,000 ÷ 1,000 = ₹50 per unit.'},
    {id:'e17',category:'Bonds',type:'mcq',title:'Bond Basics',story:'A company issues a bond to raise money from investors.',prompt:'What does a bond generally represent for the investor?',options:[['A','A debt claim under the bond terms'],['B','Ownership of every company asset'],['C','A guaranteed stock-market profit']],answer:'A',codeFragment:'3',hint:'Think lender rather than owner.',explanation:'A bond generally represents debt: the issuer borrows money and owes payments according to the bond terms.'},
    {id:'e18',category:'Bonds',type:'numeric',title:'Coupon Calculation',story:'A ₹10,000 bond has a 6% annual coupon rate.',prompt:'What is the annual coupon amount? (₹)',answer:'600',codeFragment:'9',hint:'Calculate 6% of the face value.',explanation:'₹10,000 × 6% = ₹600 per year, assuming the stated coupon is annual.'},
    {id:'e19',category:'Fraud',type:'mcq',title:'UPI Request',story:'A stranger says you must enter your UPI PIN to receive a refund.',prompt:'What is the safest response?',options:[['A','Enter the PIN because refunds always require it'],['B','Do not enter the PIN and verify the transaction independently'],['C','Share the PIN with the caller only']],answer:'B',codeFragment:'4',hint:'Receiving money is different from authorising a payment.',explanation:'You should not share a UPI PIN. Verify the transaction through the official app or channel.'},
    {id:'e20',category:'Fraud',type:'truefalse',title:'Urgency Warning Sign',story:'A message threatens that your account will be closed in 10 minutes unless you click a link.',prompt:'Is unusual urgency a common fraud warning sign?',options:[['TRUE','Yes'],['FALSE','No']],answer:'TRUE',codeFragment:'7',hint:'Fraudsters often pressure people into acting before checking.',explanation:'Unexpected urgency is a common warning sign, especially when combined with requests for credentials or money.'},
    {id:'e21',category:'Opportunity Cost',type:'mcq',title:'The Trade-Off',story:'You have ₹1,000 and can either buy a textbook or spend it on entertainment.',prompt:'If you buy the textbook, what is the opportunity cost?',options:[['A','The best alternative you give up'],['B','The ₹1,000 twice'],['C','Nothing, because choices have no trade-offs']],answer:'A',codeFragment:'5',hint:'Opportunity cost is about the next-best alternative.',explanation:'The opportunity cost of a choice is the value of the best alternative forgone.'},
    {id:'e22',category:'Returns',type:'numeric',title:'Simple Return',story:'You invest ₹5,000 and later receive ₹5,750 after selling the investment.',prompt:'What is the gain? (₹)',answer:'750',codeFragment:'2',hint:'Subtract the original amount from the final amount.',explanation:'₹5,750 − ₹5,000 = ₹750 gain, before considering any fees or taxes.'},
    {id:'e23',category:'Cash Flow',type:'mcq',title:'Cash In vs Cash Out',story:'A small club receives ₹12,000 in membership fees and pays ₹7,000 for event costs.',prompt:'What is the net cash flow from these two items?',options:[['A','+₹5,000'],['B','+₹19,000'],['C','−₹5,000']],answer:'A',codeFragment:'8',hint:'Cash received minus cash paid.',explanation:'₹12,000 − ₹7,000 = +₹5,000.'},
    {id:'e24',category:'Liquidity',type:'mcq',title:'Most Liquid',story:'You need money today for an unexpected expense.',prompt:'Which is generally the most liquid option?',options:[['A','Cash in an accessible bank account'],['B','A property that may take months to sell'],['C','A long lock-in investment']],answer:'A',codeFragment:'6',hint:'Liquidity means how quickly an asset can be converted to usable cash.',explanation:'Accessible cash or bank balances are generally more liquid than property or long lock-in investments.'}
  ],
  moderate: [
    {id:'m01',category:'Budgeting',type:'numeric',title:'Zero-Based Budget Check',story:'Monthly take-home income is ₹52,000. Fixed costs are ₹21,500 and variable essentials are ₹12,750.',prompt:'How much remains before discretionary spending and savings? (₹)',answer:'17750',codeFragment:'6',hint:'Subtract both groups of expenses from income.',explanation:'₹52,000 − ₹21,500 − ₹12,750 = ₹17,750.'},
    {id:'m02',category:'Budgeting',type:'mcq',title:'Cash-Flow Mismatch',story:'A person earns ₹40,000 on the 30th but has ₹18,000 of bills due on the 10th.',prompt:'What is the most relevant issue?',options:[['A','Cash-flow timing'],['B','The person has no annual income'],['C','The bills disappear because income is monthly']],answer:'A',codeFragment:'2',hint:'Income amount and income timing are different questions.',explanation:'A person can have sufficient monthly income but still face a timing problem if bills are due before the income arrives.'},
    {id:'m03',category:'Simple Interest',type:'numeric',title:'Loan Interest',story:'A ₹30,000 loan charges simple interest of 8% per year for 18 months.',prompt:'How much simple interest accrues? (₹)',answer:'3600',codeFragment:'8',hint:'18 months = 1.5 years.',explanation:'₹30,000 × 8% × 1.5 = ₹3,600.'},
    {id:'m04',category:'Compound Interest',type:'numeric',title:'Two-Year Growth',story:'₹10,000 is invested at 10% per year, compounded annually, with no withdrawals.',prompt:'What is the value after 2 years? (₹)',answer:'12100',codeFragment:'4',hint:'Apply 10% growth twice: 10,000 × 1.10 × 1.10.',explanation:'Year 1 = ₹11,000. Year 2 = ₹12,100.'},
    {id:'m05',category:'Inflation',type:'numeric',title:'Real Spending Power',story:'A monthly grocery budget is ₹6,000. Prices rise by 8%, but the budget stays unchanged.',prompt:'What amount would buy the same basket after the price rise? (₹)',answer:'6480',codeFragment:'1',hint:'Increase ₹6,000 by 8%.',explanation:'₹6,000 × 1.08 = ₹6,480.'},
    {id:'m06',category:'Inflation',type:'mcq',title:'Nominal vs Real',story:'An investment earns 7% while inflation is 5% over the same period.',prompt:'Ignoring taxes and other effects, which statement is most appropriate?',options:[['A','The real gain is roughly 2 percentage points using a simple approximation'],['B','The real gain must be 12%'],['C','Inflation has no effect on purchasing power']],answer:'A',codeFragment:'9',hint:'A common approximation is nominal return minus inflation.',explanation:'7% − 5% ≈ 2% as a simple real-return approximation. The exact real return is slightly different.'},
    {id:'m07',category:'Banking',type:'mcq',title:'Reconciliation',story:'Your bank statement shows ₹18,450, while your personal cashbook shows ₹19,150 because one ₹700 debit has not yet been recorded in the cashbook.',prompt:'After recording the missing debit, what should the cashbook balance become?',options:[['A','₹18,450'],['B','₹19,850'],['C','₹17,750']],answer:'A',codeFragment:'3',hint:'Record the missing ₹700 payment as an outflow.',explanation:'₹19,150 − ₹700 = ₹18,450.'},
    {id:'m08',category:'Banking',type:'mcq',title:'NEFT vs UPI Thinking',story:'A club needs to transfer a larger amount to a known beneficiary and wants to use a bank transfer channel.',prompt:'What should the club verify before authorising the transfer?',options:[['A','Beneficiary details and amount'],['B','Only the beneficiary’s profile picture'],['C','Nothing if the request sounds urgent']],answer:'A',codeFragment:'7',hint:'Payment errors can be costly even when no fraud is involved.',explanation:'Verifying beneficiary details and amount helps prevent mistaken transfers and is a basic payment-control step.'},
    {id:'m09',category:'Credit',type:'numeric',title:'Credit Utilisation',story:'A credit card has a ₹50,000 limit. The current statement balance is ₹12,500.',prompt:'What percentage of the limit is currently used? (%)',answer:'25',codeFragment:'5',hint:'Balance ÷ limit × 100.',explanation:'₹12,500 ÷ ₹50,000 × 100 = 25%.'},
    {id:'m10',category:'Credit',type:'mcq',title:'Minimum Due Trap',story:'A card statement shows total dues of ₹20,000 and a minimum due of ₹1,000.',prompt:'What is the safest interpretation?',options:[['A','Paying only the minimum necessarily clears the entire balance'],['B','The minimum due is only the minimum required payment under the statement terms'],['C','The minimum due is the same as the credit limit']],answer:'B',codeFragment:'2',hint:'Minimum payment and full repayment are not the same thing.',explanation:'A minimum due is a required minimum payment; interest and other charges may apply to unpaid balances depending on the card terms.'},
    {id:'m11',category:'Insurance',type:'numeric',title:'Deductible Logic',story:'A covered repair costs ₹18,000. The policy has a ₹5,000 deductible, assuming the claim is otherwise fully covered.',prompt:'How much would the insurer pay? (₹)',answer:'13000',codeFragment:'8',hint:'Subtract the deductible from the covered loss.',explanation:'₹18,000 − ₹5,000 = ₹13,000.'},
    {id:'m12',category:'Insurance',type:'mcq',title:'Underinsurance',story:'A person insures a ₹10 lakh asset for only ₹4 lakh and the policy applies proportional settlement rules.',prompt:'What should the person understand?',options:[['A','The policy may not fully cover a large loss'],['B','The insurer must always pay ₹10 lakh'],['C','The premium determines the asset’s market value']],answer:'A',codeFragment:'6',hint:'Coverage amount matters when a loss occurs.',explanation:'If the insured amount is below the relevant value and proportional settlement applies, the claim may not fully cover the loss.'},
    {id:'m13',category:'Investing',type:'mcq',title:'Diversification vs Guarantee',story:'Portfolio A holds shares of 12 unrelated companies. Portfolio B holds one company.',prompt:'What can diversification help with?',options:[['A','Reducing concentration risk'],['B','Guaranteeing a positive return'],['C','Eliminating market risk entirely']],answer:'A',codeFragment:'4',hint:'Diversification spreads exposure but cannot guarantee returns.',explanation:'Diversification can reduce concentration risk, but it cannot eliminate market-wide risk or guarantee profits.'},
    {id:'m14',category:'Returns',type:'numeric',title:'Percentage Return',story:'An investment rises from ₹24,000 to ₹27,000, ignoring fees and taxes.',prompt:'What is the percentage return? (%)',answer:'12.5',codeFragment:'9',hint:'Gain ÷ original value × 100.',explanation:'Gain = ₹3,000. ₹3,000 ÷ ₹24,000 × 100 = 12.5%.'},
    {id:'m15',category:'Mutual Funds',type:'mcq',title:'Expense Ratio',story:'Two otherwise similar funds have expense ratios of 0.5% and 1.5%.',prompt:'What does the expense ratio represent?',options:[['A','A recurring fund expense expressed as a percentage of assets'],['B','A guaranteed annual investor profit'],['C','A tax charged only when you sell a house']],answer:'A',codeFragment:'1',hint:'It is a fund-level operating expense measure.',explanation:'The expense ratio indicates recurring expenses charged by a fund relative to its assets, subject to the fund’s structure and disclosures.'},
    {id:'m16',category:'Bonds',type:'mcq',title:'Bond Price and Yield',story:'Market interest rates rise after a fixed-coupon bond has been issued.',prompt:'What generally happens to the market price of an existing fixed-rate bond, all else equal?',options:[['A','It tends to fall'],['B','It must rise'],['C','It becomes exactly equal to its face value']],answer:'A',codeFragment:'7',hint:'Existing coupons become relatively less attractive when new rates are higher.',explanation:'For existing fixed-coupon bonds, higher market yields generally correspond to lower prices, all else equal.'},
    {id:'m17',category:'EMI',type:'numeric',title:'Flat Monthly Budget',story:'A no-interest loan of ₹60,000 is to be repaid equally over 12 months.',prompt:'What is the monthly principal repayment? (₹)',answer:'5000',codeFragment:'3',hint:'Divide the principal equally across 12 months.',explanation:'₹60,000 ÷ 12 = ₹5,000 per month.'},
    {id:'m18',category:'Opportunity Cost',type:'mcq',title:'Capital Allocation',story:'A committee has ₹50,000. It can fund an event or buy equipment that will be useful for future events.',prompt:'What should the committee compare before deciding?',options:[['A','The benefits and opportunity costs of both uses'],['B','Only which option looks more exciting'],['C','Only the sticker price, ignoring future use']],answer:'A',codeFragment:'5',hint:'Good decisions compare what you gain and what you give up.',explanation:'Opportunity cost requires considering the best alternative use of the same resources.'},
    {id:'m19',category:'Fraud',type:'mcq',title:'QR Code Scam',story:'A seller says, “Scan this QR code and enter your UPI PIN to receive your refund.”',prompt:'What is the safest action?',options:[['A','Enter the PIN to receive the refund'],['B','Stop and verify the refund through the official payment channel'],['C','Send your PIN by text instead']],answer:'B',codeFragment:'8',hint:'A UPI PIN authorises payments; it is not something to share.',explanation:'Do not disclose a UPI PIN. Verify refund details independently through the official app or merchant channel.'},
    {id:'m20',category:'Fraud',type:'truefalse',title:'Look-Alike Domain',story:'A login page uses a domain with one extra character compared with the company’s real domain.',prompt:'Should that difference be treated as a possible phishing warning sign?',options:[['TRUE','Yes'],['FALSE','No']],answer:'TRUE',codeFragment:'6',hint:'Small spelling changes can be used in impersonation.',explanation:'Look-alike domains are a known phishing technique; users should verify the domain before entering credentials.'},
    {id:'m21',category:'Taxes',type:'numeric',title:'Taxable Portion',story:'A freelancer earns ₹80,000 from a project. An allowed business expense of ₹20,000 reduces the taxable business profit for this simplified question.',prompt:'What is the simplified taxable profit before any other adjustments? (₹)',answer:'60000',codeFragment:'2',hint:'Subtract the stated allowed expense.',explanation:'₹80,000 − ₹20,000 = ₹60,000. Actual tax calculations depend on applicable law and deductions.'},
    {id:'m22',category:'Liquidity',type:'mcq',title:'Emergency Fund vs Lock-In',story:'You need an emergency reserve that may be needed tomorrow.',prompt:'Which characteristic is least suitable for the emergency reserve?',options:[['A','Easy access'],['B','Low volatility'],['C','A long lock-in with penalties for early withdrawal']],answer:'C',codeFragment:'9',hint:'Emergency money should not be difficult to access.',explanation:'A long lock-in can make emergency funds unavailable when needed.'},
    {id:'m23',category:'Cash Flow',type:'numeric',title:'Net Operating Cash',story:'A student club receives ₹45,000 sponsorship cash and pays ₹18,000 for venue, ₹7,500 for printing, and ₹4,500 for transport.',prompt:'What is the net cash flow from these items? (₹)',answer:'15000',codeFragment:'4',hint:'45,000 − 18,000 − 7,500 − 4,500.',explanation:'Total outflow is ₹30,000, so net cash flow is ₹15,000.'},
    {id:'m24',category:'Time Value',type:'mcq',title:'Today vs Later',story:'You can receive ₹10,000 today or the same ₹10,000 exactly one year from now.',prompt:'Ignoring unusual circumstances, why can receiving it today be financially valuable?',options:[['A','Money today can potentially be invested or used productively'],['B','Future money is always worth zero'],['C','Money today automatically doubles']],answer:'A',codeFragment:'7',hint:'Think about what the money could do during the year.',explanation:'Money available today has the potential to earn a return or be used productively during the waiting period.'}
  ],
  finance: [
    {id:'f01',category:'Budgeting',type:'numeric',title:'Contribution Margin',story:'A student venture sells 200 units at ₹450 each. Variable cost is ₹280 per unit and fixed monthly costs are ₹18,000.',prompt:'What is the operating surplus before other costs? (₹)',answer:'16000',codeFragment:'8',hint:'Revenue − variable costs − fixed costs.',explanation:'Revenue = ₹90,000. Variable cost = ₹56,000. ₹90,000 − ₹56,000 − ₹18,000 = ₹16,000.'},
    {id:'f02',category:'Budgeting',type:'mcq',title:'Break-Even Thinking',story:'A project has fixed costs of ₹30,000 and earns ₹150 contribution per unit sold.',prompt:'Approximately how many units are needed to break even?',options:[['A','100'],['B','200'],['C','450']],answer:'B',codeFragment:'3',hint:'Fixed cost ÷ contribution per unit.',explanation:'₹30,000 ÷ ₹150 = 200 units.'},
    {id:'f03',category:'Compound Interest',type:'numeric',title:'Three-Year Compounding',story:'₹20,000 grows at 8% annually, compounded once per year, with no deposits or withdrawals.',prompt:'What is the approximate value after 3 years? (₹)',answer:'25194.24',codeFragment:'5',hint:'20,000 × 1.08³.',explanation:'₹20,000 × 1.08³ = ₹25,194.24.'},
    {id:'f04',category:'Compound Interest',type:'numeric',title:'Doubling Time Approximation',story:'An investment grows at 10% annually with annual compounding.',prompt:'Using the Rule of 72, approximately how many years would it take to double?',answer:'7.2',codeFragment:'2',hint:'Rule of 72: 72 ÷ rate.',explanation:'72 ÷ 10 ≈ 7.2 years. It is an approximation, not a guarantee.'},
    {id:'f05',category:'Inflation',type:'numeric',title:'Real Return',story:'A portfolio earns 9% nominally while inflation is 4%. Use the exact Fisher-style calculation for this question.',prompt:'What is the approximate real return? (%)',answer:'4.8077',accepted:['4.81','4.8077','4.8'],codeFragment:'7',hint:'Real return = (1 + nominal)/(1 + inflation) − 1.',explanation:'1.09 ÷ 1.04 − 1 ≈ 0.048077, or about 4.81%.'},
    {id:'f06',category:'Inflation',type:'mcq',title:'Real Debt Burden',story:'A borrower has a fixed nominal debt payment while inflation rises unexpectedly.',prompt:'What can inflation do to the real burden of fixed nominal payments, all else equal?',options:[['A','Reduce their real purchasing-power burden'],['B','Always increase the real burden'],['C','Have no possible effect']],answer:'A',codeFragment:'4',hint:'Think about the value of money changing over time.',explanation:'Higher prices can reduce the purchasing-power value of fixed nominal payments, although the overall effect depends on wages, rates and other factors.'},
    {id:'f07',category:'Banking',type:'numeric',title:'Effective Annual Rate',story:'A deposit advertises 12% nominal annual interest compounded monthly.',prompt:'What is the approximate effective annual rate? (%)',answer:'12.6825',accepted:['12.68','12.6825'],codeFragment:'9',hint:'EAR = (1 + 0.12/12)^12 − 1.',explanation:'(1 + 0.12/12)^12 − 1 ≈ 12.6825%.'},
    {id:'f08',category:'Banking',type:'mcq',title:'Liquidity vs Solvency',story:'A company owns valuable equipment but cannot meet a payment due tomorrow.',prompt:'Which issue is most directly illustrated?',options:[['A','Liquidity risk'],['B','Guaranteed profitability'],['C','Diversification benefit']],answer:'A',codeFragment:'1',hint:'Liquidity is about meeting near-term obligations.',explanation:'A company can own valuable long-term assets yet still face a liquidity problem if it cannot meet near-term cash obligations.'},
    {id:'f09',category:'Credit',type:'numeric',title:'Weighted Credit Cost',story:'A borrower has ₹40,000 at an annual rate of 12% and ₹60,000 at an annual rate of 8%.',prompt:'What is the weighted average interest rate on the ₹100,000 total balance? (%)',answer:'9.6',codeFragment:'6',hint:'(40,000×12% + 60,000×8%) ÷ 100,000.',explanation:'Interest-weighted rate = (₹4,800 + ₹4,800) ÷ ₹100,000 = 9.6%.'},
    {id:'f10',category:'Credit',type:'mcq',title:'APR vs Principal',story:'A loan has a stated annual rate plus processing fees.',prompt:'Why can the total borrowing cost be higher than the simple interest-rate headline suggests?',options:[['A','Fees and other charges can add to the borrowing cost'],['B','Principal is always free'],['C','Interest rates never matter']],answer:'A',codeFragment:'3',hint:'Look beyond one percentage printed in an advertisement.',explanation:'Borrowing costs can include interest, fees and other charges depending on the product and terms.'},
    {id:'f11',category:'Insurance',type:'numeric',title:'Coinsurance Split',story:'A covered loss is ₹50,000. The policy requires the insured to bear 20% coinsurance, with no deductible.',prompt:'How much would the insurer pay? (₹)',answer:'40000',codeFragment:'5',hint:'Insurer share is 80%.',explanation:'20% of ₹50,000 = ₹10,000 borne by the insured, leaving ₹40,000 for the insurer.'},
    {id:'f12',category:'Insurance',type:'mcq',title:'Moral Hazard',story:'After obtaining insurance, a person becomes less careful because they expect the insurer to bear losses.',prompt:'What insurance concept does this behaviour resemble?',options:[['A','Moral hazard'],['B','Diversification'],['C','Liquidity'],['D','Inflation']],answer:'A',codeFragment:'8',hint:'Think about behaviour changing after protection is obtained.',explanation:'Moral hazard refers to changes in behaviour that can increase risk after protection is in place.'},
    {id:'f13',category:'Investing',type:'numeric',title:'Portfolio Return',story:'₹40,000 is invested in Asset A returning 5%, and ₹60,000 in Asset B returning 10%.',prompt:'What is the portfolio’s weighted return? (%)',answer:'8',codeFragment:'2',hint:'Weight each return by the amount invested.',explanation:'(40% × 5%) + (60% × 10%) = 2% + 6% = 8%.'},
    {id:'f14',category:'Investing',type:'mcq',title:'Correlation and Diversification',story:'Two assets have returns that often move differently from each other.',prompt:'Why can lower correlation be useful in a portfolio?',options:[['A','It can reduce portfolio volatility through diversification'],['B','It guarantees both assets will rise'],['C','It eliminates every type of risk']],answer:'A',codeFragment:'7',hint:'Diversification works best when holdings do not move identically.',explanation:'Lower correlation can reduce portfolio volatility because gains and losses may partially offset each other.'},
    {id:'f15',category:'Returns',type:'numeric',title:'CAGR',story:'An investment grows from ₹10,000 to ₹14,641 over 4 years.',prompt:'What annual compound growth rate produced this value? (%)',answer:'10',accepted:['10','10.0'],codeFragment:'4',hint:'10,000 × (1+r)^4 = 14,641.',explanation:'14,641 ÷ 10,000 = 1.4641 = 1.1^4, so the CAGR is 10%.'},
    {id:'f16',category:'Returns',type:'numeric',title:'Total Return with Income',story:'A share is bought for ₹2,000, sold for ₹2,180, and paid ₹60 in dividends during the holding period.',prompt:'What is the total return percentage? (%)',answer:'12',codeFragment:'9',hint:'Price gain + dividend, divided by purchase price.',explanation:'Total gain = ₹180 + ₹60 = ₹240. ₹240 ÷ ₹2,000 × 100 = 12%.'},
    {id:'f17',category:'Bonds',type:'mcq',title:'Duration Intuition',story:'Two fixed-rate bonds are otherwise similar, but Bond A has a longer duration than Bond B.',prompt:'If market yields rise, which bond generally experiences the larger percentage price change?',options:[['A','Bond A'],['B','Bond B'],['C','They must move identically']],answer:'A',codeFragment:'1',hint:'Duration measures sensitivity to yield changes.',explanation:'All else equal, longer-duration bonds are generally more sensitive to changes in market yields.'},
    {id:'f18',category:'Bonds',type:'numeric',title:'Current Yield',story:'A bond pays an annual coupon of ₹800 and currently trades for ₹9,500.',prompt:'What is its approximate current yield? (%)',answer:'8.4211',accepted:['8.42','8.4211'],codeFragment:'6',hint:'Annual coupon ÷ current market price × 100.',explanation:'₹800 ÷ ₹9,500 × 100 ≈ 8.42%.'},
    {id:'f19',category:'Mutual Funds',type:'mcq',title:'Active vs Passive',story:'Fund A tracks a market index with low fees. Fund B has a manager selecting securities and charges higher fees.',prompt:'Which description best fits Fund A?',options:[['A','Passive/index-tracking approach'],['B','Guaranteed-return approach'],['C','Insurance-only approach']],answer:'A',codeFragment:'3',hint:'Tracking an index is the key clue.',explanation:'A fund designed to track an index is generally described as passive or index-tracking.'},
    {id:'f20',category:'Mutual Funds',type:'numeric',title:'NAV After Gain',story:'A fund has 2,000 units and net assets of ₹1,00,000. The portfolio gains ₹10,000 with no cash flows.',prompt:'What is the new NAV per unit? (₹)',answer:'55',codeFragment:'8',hint:'New net assets = ₹1,10,000. Divide by 2,000 units.',explanation:'₹1,10,000 ÷ 2,000 = ₹55 per unit.'},
    {id:'f21',category:'Taxes',type:'mcq',title:'Marginal Rate',story:'A progressive tax system has different rates for different portions of taxable income.',prompt:'Does reaching a higher bracket necessarily mean every rupee of income is taxed at the highest rate?',options:[['A','No, only the income within the relevant bracket is taxed at that marginal rate'],['B','Yes, every rupee is automatically taxed at the top rate'],['C','Tax brackets never affect tax calculations']],answer:'A',codeFragment:'5',hint:'Marginal means the rate on the next slice of taxable income.',explanation:'In a progressive system, different portions can be taxed at different rates. Actual rules vary by jurisdiction and tax regime.'},
    {id:'f22',category:'Opportunity Cost',type:'numeric',title:'Capital Choice',story:'A club can use ₹1,00,000 to earn a guaranteed ₹8,000 from a project or use it for an alternative project expected to generate ₹12,000.',prompt:'What is the opportunity cost of choosing the ₹8,000 project, using the stated expected benefit of the alternative? (₹)',answer:'12000',codeFragment:'2',hint:'Opportunity cost is the best alternative forgone.',explanation:'The stated alternative would generate ₹12,000, so that is the opportunity cost of choosing the other project under this simplified comparison.'},
    {id:'f23',category:'Fraud',type:'mcq',title:'Business Email Compromise',story:'An executive email asks the finance team to urgently change a supplier’s bank account before today’s payment.',prompt:'What control is most appropriate?',options:[['A','Verify the change through an independent known contact before payment'],['B','Change the account immediately because the email uses the correct logo'],['C','Send the payment first and verify later']],answer:'A',codeFragment:'7',hint:'Use a second channel that was not supplied by the suspicious message.',explanation:'Independent verification is a common control against payment redirection and impersonation fraud.'},
    {id:'f24',category:'Fraud',type:'truefalse',title:'Social Engineering',story:'A caller uses publicly available information about an employee to sound convincing.',prompt:'Can accurate personal details still be used as part of a fraud attempt?',options:[['TRUE','Yes'],['FALSE','No']],answer:'TRUE',codeFragment:'4',hint:'Knowing real details does not prove the caller is genuine.',explanation:'Fraudsters can use real information to build trust. Identity and payment requests should still be verified through trusted channels.'}
  ]
};

if (typeof window !== 'undefined') window.QUESTION_BANK = QUESTION_BANK;
